import { Category, Provider } from '@/types';

export const CATEGORIES: Category[] = [
  {
    id: 'home-improvement',
    name: 'Home Improvement',
    description: 'Find professionals for repairs, renovations, and home maintenance services',
    icon: 'https://images.pexels.com/photos/3990359/pexels-photo-3990359.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    subcategories: ['Plumbing', 'Electrical', 'HVAC', 'Carpentry', 'Painting', 'Roofing'],
    providerCount: 1240,
  },
  {
    id: 'cleaning',
    name: 'Cleaning Services',
    description: 'Professional cleaning services for homes, offices, and specialized cleaning needs',
    icon: 'https://images.pexels.com/photos/4107112/pexels-photo-4107112.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    subcategories: ['House Cleaning', 'Office Cleaning', 'Carpet Cleaning', 'Window Cleaning', 'Deep Cleaning'],
    providerCount: 853,
  },
  {
    id: 'personal',
    name: 'Personal Services',
    description: 'Services for personal care, wellness, and lifestyle needs',
    icon: 'https://images.pexels.com/photos/3992874/pexels-photo-3992874.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    subcategories: ['Personal Training', 'Massage Therapy', 'Hair & Beauty', 'Life Coaching', 'Personal Shopping'],
    providerCount: 732,
  },
  {
    id: 'events',
    name: 'Event Services',
    description: 'Professional services for planning and executing memorable events',
    icon: 'https://images.pexels.com/photos/2774556/pexels-photo-2774556.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    subcategories: ['Event Planning', 'Catering', 'Photography', 'Entertainment', 'Decor'],
    providerCount: 428,
  },
  {
    id: 'lessons',
    name: 'Lessons & Training',
    description: 'Expert instructors for various skills and educational needs',
    icon: 'https://images.pexels.com/photos/8926556/pexels-photo-8926556.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    subcategories: ['Music Lessons', 'Language Training', 'Academic Tutoring', 'Sports Coaching', 'Art Classes'],
    providerCount: 512,
  },
  {
    id: 'business',
    name: 'Business Services',
    description: 'Professional services to help your business grow and succeed',
    icon: 'https://images.pexels.com/photos/3184405/pexels-photo-3184405.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    subcategories: ['Consulting', 'Marketing', 'Accounting', 'Legal Services', 'IT Support'],
    providerCount: 672,
  },
  {
    id: 'health',
    name: 'Health & Wellness',
    description: 'Services focused on health, fitness, and overall wellbeing',
    icon: 'https://images.pexels.com/photos/3757942/pexels-photo-3757942.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    subcategories: ['Fitness Training', 'Nutrition', 'Mental Health', 'Physical Therapy', 'Alternative Medicine'],
    providerCount: 389,
  },
  {
    id: 'tech',
    name: 'Tech Services',
    description: 'Technical solutions and support for all your digital needs',
    icon: 'https://images.pexels.com/photos/6192595/pexels-photo-6192595.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    subcategories: ['Web Development', 'IT Support', 'Digital Marketing', 'App Development', 'Cybersecurity'],
    providerCount: 517,
  }
];

export const PROVIDERS: Provider[] = [
  {
    id: '1',
    name: 'Premier Plumbing Solutions',
    category: 'Home Improvement',
    rating: 4.9,
    reviewCount: 187,
    location: 'San Francisco, CA',
    image: 'https://images.pexels.com/photos/8005380/pexels-photo-8005380.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    verified: true,
    vettedPro: true,
    hourlyRate: 85,
    availability: ['Weekdays', 'Weekends', 'Emergency'],
    services: ['Plumbing Repair', 'Drain Cleaning', 'Fixture Installation'],
    description: 'Professional plumbing services with 15+ years of experience. Available 24/7 for emergency repairs.',
    about: 'Premier Plumbing Solutions has been serving the San Francisco Bay Area for over 15 years. We pride ourselves on providing reliable, high-quality plumbing services with transparent pricing and exceptional customer service.',
    verifications: {
      idVerified: true,
      businessLicense: true,
      insurance: true,
      backgroundCheck: true,
    },
    gallery: [
      'https://images.pexels.com/photos/8005380/pexels-photo-8005380.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/8005383/pexels-photo-8005383.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/8005397/pexels-photo-8005397.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    responseTime: '25min',
  },
  {
    id: '2',
    name: 'Sparkling Clean Services',
    category: 'Cleaning',
    rating: 4.8,
    reviewCount: 143,
    location: 'Oakland, CA',
    image: 'https://images.pexels.com/photos/3768911/pexels-photo-3768911.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    verified: true,
    vettedPro: false,
    hourlyRate: 65,
    availability: ['Weekdays', 'Weekends'],
    services: ['House Cleaning', 'Deep Cleaning', 'Move Out Cleaning'],
    description: 'Professional cleaning services with attention to detail and eco-friendly products.',
    about: 'Sparkling Clean Services has been providing top-quality cleaning services in the Bay Area for over 10 years. We use eco-friendly products and thorough cleaning techniques to ensure your space is spotless.',
    verifications: {
      idVerified: true,
      businessLicense: true,
      insurance: true,
      backgroundCheck: true,
    },
    gallery: [
      'https://images.pexels.com/photos/3768911/pexels-photo-3768911.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/4107112/pexels-photo-4107112.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    responseTime: '30min',
  },
  {
    id: '3',
    name: 'Elite Electrical Contractors',
    category: 'Home Improvement',
    rating: 4.7,
    reviewCount: 112,
    location: 'San Jose, CA',
    image: 'https://images.pexels.com/photos/8005383/pexels-photo-8005383.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    verified: true,
    vettedPro: true,
    hourlyRate: 95,
    availability: ['Weekdays', 'Emergency'],
    services: ['Electrical Repair', 'Wiring', 'Lighting Installation'],
    description: 'Licensed electrical contractors providing comprehensive electrical services.',
    about: 'Elite Electrical Contractors is a team of licensed and experienced electricians serving the Bay Area. We handle everything from simple repairs to complex installations with precision and safety.',
    verifications: {
      idVerified: true,
      businessLicense: true,
      insurance: true,
      backgroundCheck: true,
    },
    gallery: [
      'https://images.pexels.com/photos/8005383/pexels-photo-8005383.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/8005397/pexels-photo-8005397.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    responseTime: '20min',
  },
  {
    id: '4',
    name: 'Landscape Masters',
    category: 'Home Improvement',
    rating: 4.9,
    reviewCount: 156,
    location: 'Palo Alto, CA',
    image: 'https://images.pexels.com/photos/4503272/pexels-photo-4503272.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    verified: false,
    vettedPro: false,
    hourlyRate: 75,
    availability: ['Weekdays', 'Weekends'],
    services: ['Garden Design', 'Lawn Care', 'Tree Services'],
    description: 'Professional landscaping services for residential and commercial properties.',
    about: 'Landscape Masters specializes in creating and maintaining beautiful outdoor spaces. Our team of experts handles everything from garden design to regular maintenance.',
    verifications: {
      idVerified: true,
      businessLicense: true,
      insurance: true,
      backgroundCheck: false,
    },
    gallery: [
      'https://images.pexels.com/photos/4503272/pexels-photo-4503272.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/4503273/pexels-photo-4503273.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
    responseTime: '1hr',
  },
];

export const POPULAR_SERVICES = [
  'Plumbing',
  'House Cleaning',
  'Electrician',
  'Landscaping',
  'Moving',
];

export const AVAILABILITY_OPTIONS = [
  'Weekdays',
  'Weekends',
  'Evenings',
  'Emergency',
]; 